/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAffix: typeof import("element-plus/es")["ElAffix"]
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import("element-plus/es")["ElCol"]
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"]
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import("element-plus/es")["ElOption"]
    ElRadio: typeof import("element-plus/es")["ElRadio"]
    ElRadioButton: typeof import("element-plus/es")["ElRadioButton"]
    ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"]
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"]
    ElSelect: typeof import("element-plus/es")["ElSelect"]
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import("element-plus/es")["ElSwitch"]
    ElTimePicker: typeof import("element-plus/es")["ElTimePicker"]
    Index: typeof import('./src/components/loading/Index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
